
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  #boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  
  boot.extraModulePackages = [ config.boot.kernelPackages.rtl88xxau-aircrack ];

  boot.extraModprobeConfig = ''
    options cfg80211 ieee80211_regdom="SE"
  '';

  hardware.wirelessRegulatoryDatabase = true;
  boot.initrd.kernelModules = [  ];
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7ca8966f-1174-4ef8-ae67-da6b3f0c7f2b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5050-1206";
      fsType = "vfat";
    };

  swapDevices = [ 
	{ device = "/dev/disk/by-uuid/7694785a-ff17-4d19-bcce-7637d74f0789";
    #    size = 8*1024;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
